version: '3.8'
services:

  node:
    build: 
      context: app
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - '8000:8000'
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - codeTest:/data/db
volumes:
  codeTest:  